import numpy as np
import matplotlib.pyplot as plt
from scipy import interpolate

# Read gridlength
f=open('../../Single_Carbon/C_Atom_0/XAS_shift.dat','r')
loc=f.readlines()
f.close()
GridX=len(loc)

FREQ=np.zeros((xxxaxxx,GridX))		# xxxaxxx will be substituted inside the XASSPEC.sh, that is generated by the ShiftXas.py
VEC=np.zeros((xxxaxxx,GridX))

# Read all Vectors
for i in range(0,xxxaxxx):
 g=open('../../Single_Carbon/C_Atom_'+str(i)+'/XAS_shift.dat','r')
 loc=g.readlines()
 g.close()
 
 for j in range(len(loc)):
  FREQ[i,j]=float(loc[j].split()[0])
  VEC[i,j]+=float(loc[j].split()[1])

#initialize the Sumvector
bottom=FREQ.min()
shelf=FREQ.max()
#print bottom, shelf
FREQVEC=np.arange(bottom,shelf,FREQ[0,1]-FREQ[0,0])
GridY=len(FREQVEC)
SUMVEC=np.zeros((GridY))

for k in range(xxxaxxx):
# print "Atom number", k
 count=0
 for i in range(GridY):
  if abs(FREQ[k,count]-FREQVEC[i])>0.009:
   SUMVEC[i]=SUMVEC[i]+0.0

  else:
#   print "found starting point", FREQ[k,count], "is equal", FREQVEC[i]
   for j in range(GridX):
    SUMVEC[i+j]=SUMVEC[i+j]+VEC[k,j]
   break

h=open('./XAS_SUM.dat','w')
for i in range(GridY):
 h.write(str(FREQVEC[i])+"       "+str(SUMVEC[i])+"\n")
h.close()
